### ISSUE TITLE
Cannot index many full-length genomes with unknown characters

### ISSUE THREAD

**Issue by apetkau** [apetkau/genomics-data-index#67]
If I currently try to load full-length genomes and index unknown (ambiguous/gap) characters I get the following:

```
2021-07-22 10:42:20 DEBUG genomics_data_index.storage.service.FeatureService.index_features,227: Indexing a total of 550901 features
Traceback (most recent call last):
  File "/home/apetkau/miniconda3/envs/thesis-index/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1706, in _execute_context
    self.dialect.do_execute(
  File "/home/apetkau/miniconda3/envs/thesis-index/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 716, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: too many SQL variables

The above exception was the direct cause of the following exception:
...
  File "/home/apetkau/miniconda3/envs/thesis-index/lib/python3.8/site-packages/genomics_data_index/cli/gdi.py", line 178, in load_snippy
    load_variants_common(data_index_connection=data_index_connection, ncores=ncores, data_package=data_package,
  File "/home/apetkau/miniconda3/envs/thesis-index/lib/python3.8/site-packages/genomics_data_index/cli/gdi.py", line 131, in load_variants_common
    variation_service.insert(feature_scope_name=reference_name,
  File "/home/apetkau/miniconda3/envs/thesis-index/lib/python3.8/site-packages/genomics_data_index/storage/service/FeatureService.py", line 174, in insert
    self.index_features(features_reader=persisted_features_reader, feature_scope_name=feature_scope_name)
  File "/home/apetkau/miniconda3/envs/thesis-index/lib/python3.8/site-packages/genomics_data_index/storage/service/FeatureService.py", line 228, in index_features
    db_feature_objects_dict = self.read_index(list(created_feature_objects_dict.keys()))
  File "/home/apetkau/miniconda3/envs/thesis-index/lib/python3.8/site-packages/genomics_data_index/storage/service/VariationService.py", line 263, in read_index
    feature_samples = self._connection.get_session().query(NucleotideVariantsSamples) \
...
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) too many SQL variables
[SQL: SELECT nucleotide_variants_samples.spdi AS nucleotide_variants_samples_spdi, nucleotide_variants_samples.id_hgvs_c AS nucleotide_variants_samples_id_hgvs_c, nucleotide_variants_samples.id_hgvs_p AS nucleotide_variants_samples_id_hgvs_p, nucleotide_variants_samples.sequence AS nucleotide_variants_samples_sequence, nucleotide_variants_samples.position AS nucleotide_variants_samples_position, nucleotide_variants_samples.deletion AS nucleotide_variants_samples_deletion, nucleotide_variants_samples.insertion AS nucleotide_variants_samples_insertion, nucleotide_variants_samples.var_type AS nucleotide_variants_samples_var_type, nucleotide_variants_samples._sample_ids AS nucleotide_variants_samples__sample_ids, nucleotide_variants_samples.annotation AS nucleotide_variants_samples_annotation, nucleotide_variants_samples.annotation_impact AS nucleotide_variants_samples_annotation_impact, nucleotide_variants_samples.annotation_gene_name AS nucleotide_variants_samples_annotation_gene_name, nucleotide_variants_samples.annotation_gene_id AS nucleotide_variants_samples_annotation_gene_id, nucleotide_variants_samples.annotation_feature_type AS nucleotide_variants_samples_annotation_feature_type, nucleotide_variants_samples.annotation_transcript_biotype AS nucleotide_variants_samples_annotation_transcript_biotype, nucleotide_variants_samples.annotation_hgvs_c AS nucleotide_variants_samples_annotation_hgvs_c, nucleotide_variants_samples.annotation_hgvs_p AS nucleotide_variants_samples_annotation_hgvs_p
FROM nucleotide_variants_samples
WHERE nucleotide_variants_samples.spdi IN (?, ?, ?, ?, ?, ?...
```

I believe part of this is related to limits of SQLite and query length, but I also get a similar error if I use MariaDB (though MariaDB can support longer queries).

**Comment by apetkau** [comment]
I believe this could be related to a SQLite limit: https://stackoverflow.com/questions/26971050/sqlalchemy-sqlite-too-many-sql-variables
